services:
  log-ingest:
    image: log_panda_ingest_log_i
    container_name: log_panda_ingest_log_c
    build:
      context: ./apps/log-ingest
    ports:
      - "3003:8080"
    environment:
      PORT: 8080
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s
    networks:
      - log_panda_network


networks:
  log_panda_network:
    driver: bridge
    name: log_panda_network_n