services:
  app1:
    container_name: log_panda_app1_c
    image: log_panda_app1_i:latest
    build:
      context: ./apps/app1
    ports:
      - "3000:8080"
    environment:
      PORT: 8080
      APP_NAME: "app1"
      GENERATE_LOGS_TIME_SECONDS: 1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s

  app2:
    image: log_panda_app2_i:latest
    container_name: log_panda_app2_c
    build:
      context: ./apps/app2
    ports:
      - "3001:8080"
    environment:
      PORT: 8080
      APP_NAME: "app2"
      GENERATE_LOGS_TIME_SECONDS: 1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s


  app3:
    image: log_panda_app3_i:latest
    container_name: log_panda_app3_c
    build:
      context: ./apps/app3
    ports:
      - "3002:8080"
    environment:
      PORT: 8080
      APP_NAME: "app3"
      GENERATE_LOGS_TIME_SECONDS: 1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s
