apiVersion: v1
kind: Service
metadata:
  name: log-ingest-kafka
spec:
  selector:
    app: log-panda-log-ingest-kafka
  ports:
    - name: kafka-client
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      port: 9093
      targetPort: 9093
  type: ClusterIP