apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-panda-log-ingest-kafka
  labels:
    app: log-panda-log-ingest-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-panda-log-ingest-kafka
  template:
    metadata:
      labels:
        app: log-panda-log-ingest-kafka
    spec:
      containers:
        - name: log-panda-log-ingest-kafka-c
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@log-ingest-kafka:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://log-ingest-kafka:9092"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_LOG_DIRS
              value: "/bitnami/kafka/data" 
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-data
      volumes:
        - name: kafka-data
          emptyDir: {}              