apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-panda-log-ingest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-panda-log-ingest
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # CPU utilization target
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Memory utilization target
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
