# Build stage
FROM node:22-alpine AS build

WORKDIR /user/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . .

RUN npm run build


# Production stage
FROM node:22-alpine AS prod

WORKDIR /user/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --omit=dev

COPY --from=build ./user/src/app/dist ./dist

CMD ["npm", "start"]


